<a href="https://colab.research.google.com/github/ishancoderr/3D_modeling/blob/main/pixel_count_in_tiff.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import cv2
from PIL import Image
from numpy import asarray



In [ ]:
img = cv2.imread('/content/Rainfall_Reclassified.tif')

In [ ]:
numpydata = asarray(img)

In [ ]:
print(img)

None


In [ ]:
!pip install rasterio

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 19.3 MB 414 kB/s 


In [ ]:
import rasterio
import matplotlib.pyplot as plt
from numpy import asarray

# Open raster and plot
raster_b = rasterio.open("/content/Rainfall.tif").read(1)


In [ ]:
img=asarray(raster_b)
print(img)

[[2147483647 2147483647 2147483647 ...          2          2          2]
 [2147483647 2147483647 2147483647 ...          2          2          2]
 [2147483647 2147483647 2147483647 ...          2          2 2147483647]
 ...
 [         5          5          5 ... 2147483647 2147483647 2147483647]
 [         5          5          5 ... 2147483647 2147483647 2147483647]
 [         5          5          5 ... 2147483647 2147483647 2147483647]]


310


In [ ]:
import rasterio
from numpy import asarray

# Open raster and plot
raster_b = rasterio.open("/content/Rainfall.tif").read(1)

rows = len(img)
cols = len(img[0])


In [ ]:
d={}

for i in range(rows):
  for j in range(cols):
    if img[i,j] in d:
      d[img[i,j]]+=1
    else:
      d[img[i,j]]= 1

In [ ]:
print(d)

{2147483647: 17012, 5: 30836, 4: 67996, 3: 82476, 2: 37280}


In [ ]:
sum=0
for i,j in d.items():
  sum=sum+j

for i,j in d.items():
  print(f"{i} value :{j}/{sum}")

NameError: ignored